spring.application.name=week7-jpa

# Active profile
spring.profiles.active=dev

# JPA
spring.jpa.open-in-view=false

# Logging
logging.level.com.ashutosh.week7_jpa=DEBUG
logging.level.org.hibernate.SQL=DEBUG